# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vballtime',
                'doc_host': 'https://Gippers.github.io',
                'git_url': 'https://github.com/Gippers/vballtime',
                'lib_path': 'vballtime'},
  'syms': { 'vballtime.core': {'vballtime.core.foo': ('core.html#foo', 'vballtime/core.py')},
            'vballtime.vball_sets': { 'vballtime.vball_sets.Set': ('vball_sets.html#set', 'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.Set.GetTime': ('vball_sets.html#set.gettime', 'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.Set.__init__': ('vball_sets.html#set.__init__', 'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.Set.__repr__': ('vball_sets.html#set.__repr__', 'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.Set.__str__': ('vball_sets.html#set.__str__', 'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.foo': ('vball_sets.html#foo', 'vballtime/vball_sets.py')}}}
