# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vballtime',
                'doc_host': 'https://Gippers.github.io',
                'git_url': 'https://github.com/Gippers/vballtime',
                'lib_path': 'vballtime'},
  'syms': { 'vballtime.core': {'vballtime.core.foo': ('core.html#foo', 'vballtime/core.py')},
            'vballtime.vball_sets': { 'vballtime.vball_sets.VballSet': ('vball_sets.html#vballset', 'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.VballSet.GetTime': ( 'vball_sets.html#vballset.gettime',
                                                                                 'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.VballSet.__init__': ( 'vball_sets.html#vballset.__init__',
                                                                                  'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.VballSet.__repr__': ( 'vball_sets.html#vballset.__repr__',
                                                                                  'vballtime/vball_sets.py'),
                                      'vballtime.vball_sets.VballSet.__str__': ( 'vball_sets.html#vballset.__str__',
                                                                                 'vballtime/vball_sets.py')}}}
